name: Build APK

on:
  push:
    branches:
      - main  # هذا يعني أن GitHub سيقوم ببناء APK في كل مرة تقوم بعمل push على الفرع الرئيسي

jobs:
  build:
    runs-on: ubuntu-latest  # سيتم تنفيذ الأوامر على سيرفر يعمل بنظام Ubuntu

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # للحصول على الكود من المستودع

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # يمكنك تغيير النسخة إلى أي نسخة تحتاجها

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo apt-get install -y build-essential
        sudo apt-get install -y libssl-dev libffi-dev python3-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Run buildozer
      run: |
        buildozer -v android debug  # هذا الأمر سيقوم بعمل APK باستخدام Buildozer
